### ISSUE TITLE
Save/load is sketchy

### ISSUE THREAD

**Issue by Zireael07** [marukrap/RoguelikeTutorial2020#1]
Sometimes it saves/loads, sometimes it doesn't. I wasn't able to figure out why, as it sometimes loads after closing the browser and sometimes doesn't just after refreshing w/o closing the browser window.

Maybe a solution would be to use FS.writeFile('Save/Savefile', 'whatever') instead of ofs:ofstream? And please print a console error on failed load, to make debugging easier on both yourself and players.

**Comment by marukrap** [comment]
Yeah, I'm still testing the save system and it could be unstable. I made it with FS.writeFile() interface at first but it didn't work well when I close the tab. It only worked when I refresh the page in my case.

I couldn't find any solution or relevant information. So I just tried to use another API and it seems it works. (at least on my test) More specifically, there's a problem when you save on page closing. If you want to avoid this problem now, you can probably make in-game save menu and it will work well.

I found it also works if you add a confirmation dialog when you close the page, but I didn't like it. Anyway, the reason I guess is because they're asynchronous functions. there're also some synchronous functions in Emscripten.

What's your browser btw? I only tested it on Chrome/Edge. The save system doesn't work at all on Edge I don't know why. and the current 'part 10' may have problem when loading. I fixed it in my latest code but I just didn't update yet.

**Comment by Zireael07** [comment]
My browser is Brave (basically Chrome with some adblocker on top)

More probable, when saving on page close, the connection is aborted before the stream is fully written?

**Comment by marukrap** [comment]
Yes, or Emscripten API closes early on page close without waiting asynchronous file IO is finished. that's my guess.
